title: "[Conversation] "
labels: ["Conversation"]
body:
  - type: markdown
    attributes:
      value: |
        Explain customization summary
  
  - type: input
    id: summary
    attributes:
      label: Summary
      description: "Please provide a short description of what customization it is."
    validations:
      required: true
  
  - type: textarea
    id: guide-snippet
    attributes:
      label: Guide & Snippet
      description: "Customization 가이드와 스니펫을 넣어주세요. 플랫폼별 섹션에 입력하세요.(먼저 작성하는 플랫폼은 자신의 플랫폼만 채우고 나머지는 제거하지 마세요)"
      value: |
        <details>
        <summary>iOS</summary>
        
        #### You can add a header
        
        You can add text within a collapsed section.
        
        ```swift
           puts "Hello World"
        ```
        
        </details>

        <details>
        <summary>Android</summary>
        
        #### You can add a header
        
        You can add text within a collapsed section.
        
        ```kotlin
           puts "Hello World"
        ```
        
        </details>


        <details>
        <summary>iOS</summary>
        
        #### You can add a header
        
        You can add text within a collapsed section.
        
        ```JS
           puts "Hello World"
        ```
        
        </details>
    validations:
      required: true
  
  - type: input
    id: reference
    attributes:
      label: Reference
      description: 참고할만한 link 가 있으면 추가
      placeholder: "[TITLE](Link)"
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "스크린샷이 있다면 추가해주세요"
      value: |
        |**As-is**|**To-be**|
        |---|---|
        |<img src="" width="50%" height="50%" />|<img src="" width="50%" height="50%" />|
    validations:
      required: false

