title: "[Conversation] "
labels: ["Conversation"]
body:
  - type: markdown
    attributes:
      value: |
        Explain the customization summary
  
  - type: input
    id: summary
    attributes:
      label: Summary
      description: "Please provide a short description of what customization it is."
    validations:
      required: true
  
  - type: textarea
    id: guide-snippet-ios
    attributes:
      label: Guide & Snippet (iOS)
      description: "Customization 가이드와 스니펫을 넣어주세요. 플랫폼별 섹션에 입력하세요.(먼저 작성하는 플랫폼은 자신의 플랫폼만 채우고 나머지는 제거하지 마세요)"
      value: |
        <details>
        <summary>iOS</summary>
        
        #### Header

        - Description
        
        ```swift
           // code block
        ```
        
        </details>
    validations:
      required: false

- type: textarea
    id: guide-snippet-android
    attributes:
      label: Guide & Snippet (Android)
      description: "Customization 가이드와 스니펫을 넣어주세요. 플랫폼별 섹션에 입력하세요.(먼저 작성하는 플랫폼은 자신의 플랫폼만 채우고 나머지는 제거하지 마세요)"
      value: |
        <details>
        <summary>Android</summary>
        
        #### Header

        - Description
        
        ```kotlin
           // code block
        ```
        
        </details>
    validations:
      required: false

- type: textarea
    id: guide-snippet-js
    attributes:
      label: Guide & Snippet (JS)
      description: "Customization 가이드와 스니펫을 넣어주세요. 플랫폼별 섹션에 입력하세요.(먼저 작성하는 플랫폼은 자신의 플랫폼만 채우고 나머지는 제거하지 마세요)"
      value: |
        <details>
        <summary>JS</summary>
        
        #### Header

        - Description
        
        ```js
           // code block
        ```
        
        </details>
    validations:
      required: false
  
  - type: input
    id: reference
    attributes:
      label: Reference
      description: 참고할만한 link 가 있으면 추가
      placeholder: "- [TITLE](Link)"
    validations:
      required: false

  - type: input
    id: reference
    attributes:
      label: Screenshots
      description: 참고할만한 link 가 있으면 추가
      placeholder: |
        |**As-is**|**To-be**|
        |---|---|
        |<img src="" width="50%" height="50%" />|<img src="" width="50%" height="50%" />|
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "스크린샷이 있다면 추가해주세요"
      value: |
        |**As-is**|**To-be**|
        |---|---|
        |<img src="" width="50%" height="50%" />|<img src="" width="50%" height="50%" />|
    validations:
      required: false

