title: "[General] "
labels: ["Conversation"]
body:
  - type: markdown
    attributes:
      value: |
        Explain customization summary
  - type: input
    id: summary
    attributes:
      label: Summary
      description: "Please provide a short description of what customization it is."
    validations:
      required: true
  - type: textarea
    id: guide-snippet
    attributes:
      label: Guide & Snippet
      description: "Customization 가이드와 스니펫을 넣어주세요. 플랫폼별 섹션에 입력하세요.(먼저 작성하는 플랫폼은 자신의 플랫폼만 채우고 나머지는 제거하지 마세요)"
      value: |
        <details>
        <summary>iOS</summary>
        ### You can add a header
        You can add text within a collapsed section.
        ```swift
           puts "Hello World"
        ```
        </details>

        <details>
        <summary>Android</summary>
        ### You can add a header
        You can add text within a collapsed section.
        ```swift
           puts "Hello World"
        ```
        </details>


        <details>
        <summary>JS</summary>
        ### You can add a header
        You can add text within a collapsed section.
        ```swift
           puts "Hello World"
        ```
        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
